name: build-dev

on:
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 创建版本号
        id: set_version
        run: |
          echo "DEV_$(date -d '+8 hours' +'%Y%m%d%H%M')" > version_number
          echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version_number
  build-frontend:
    runs-on: ubuntu-latest
    needs: [ generate-version ]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Checkout code front end
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPOSITORY_FRONT }}
          path: './msaber-front'
          ref: 'main'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version
  
      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Update front version in version.ts
        run: |
          echo "export const version = '${{ env.version }}';" > msaber-front/version.ts

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            msaber-front/package-lock.json
            msaber-front/package.json
      - name: Build Frontend
        run: |
          cd msaber-front
          npm ci
          npm run build
      - name: Compress Frontend Build
        run: tar -czf msaber-front.tar.gz msaber-front
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-frontend
          path: msaber-front.tar.gz

  build-backend:
    runs-on: ubuntu-latest
    needs: [ generate-version ]
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      
      - name: Checkout code back end
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPOSITORY_BACK }}
          path: './msaber-back'
          ref: 'main'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/msaber-back/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version
  
      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Build for ${{ matrix.arch }}
        run: |
          cd msaber-back
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -a --trimpath -ldflags="-X 'github.com/xylplm/media-saber-back-end/internal/svc.sqlDebug=false' -X 'msaber-back/internal/config.Version=${{ env.version }}' -X 'msaber-back/internal/config.BuildDate=$(date)'" -o dist/linux/${{ matrix.arch }}/mediaSaber .
      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-backend-${{ matrix.arch }}
          path: msaber-back

  docker-setup:
    runs-on: ubuntu-latest
    needs: [ build-frontend, build-backend ]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact-frontend

      - name: Unzip Frontend Build
        run: tar -xzf msaber-front.tar.gz

      - run: ls -R msaber-front

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-backend-*
          merge-multiple: true
          path: msaber-back

      - run: ls -R msaber-back

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/media-saber:go-dev
          push: true
  gen-release:
    runs-on: ubuntu-latest
    needs: [docker-setup]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version
  
      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact-frontend

      - name: Unzip Frontend Build
        run: tar -xzf msaber-front.tar.gz

      - run: ls -R msaber-front

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-backend-*
          merge-multiple: true
          path: msaber-back

      - run: ls -R msaber-back

      - name: Prepare Files for Release amd64
        run: |
          mkdir -p release/msaber-front
          mkdir -p release/msaber-back
          mkdir -p release/msaber-back/doc/static
          cp -r msaber-front/dist/MediaSaber/browser/* release/msaber-front/
          cp -r msaber-back/dist/linux/amd64/mediaSaber release/msaber-back/mediaSaber
          cp -r msaber-back/etc release/msaber-back/
          cp -r msaber-back/doc/static release/msaber-back/doc/static

      - name: Create ZIP Archive amd64
        run: |
          cd release
          tar -czvf mediaSaber-amd64.tar.gz msaber-front msaber-back

      
      - name: Prepare Files for Release arm64
        run: |
          cp -r msaber-back/dist/linux/arm64/mediaSaber release/msaber-back/mediaSaber

      - name: Create ZIP Archive arm64
        run: |
          cd release
          tar -czvf mediaSaber-arm64.tar.gz msaber-front msaber-back


    
      - name: Check if release already exists
        id: check_release
        run: |
          exists=$(gh release view ${{ env.version }} 2>&1 | grep "release not found" || true)
          if [[ -z "$exists" ]]; then
            echo "Release exists"
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Release does not exist"
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Create GitHub Release if not exists
        if: env.RELEASE_EXISTS == 'false'
        run: |
          gh release create ${{ env.version }} \
            --title "${{ env.version }}" \
            --notes "Release of version ${{ env.version }}"
        env:
          GH_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Upload Asset
        run: |
          gh release upload ${{ env.version }} mediaSaber-amd64.tar.gz mediaSaber-arm64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Update version_dev File
        run: echo "${{ env.version }}" > version_dev
  
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add version_dev
          git commit -m "Update version_dev with ${{ env.version }}"
          git push
